version: '3'
services:
  postgres:
    image: postgres:13
    container_name: psql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file: 
      - .env
  backend:
    build: ./
    ports:
      - "3000:3000"
    env_file: 
      - .env
    depends_on:
      - postgres