POST http://localhost:3000/auth/register 
Content-Type: application/json

{
  "login": "Hendrykkkk",
  "email": "hellooko@hello.com",
  "password": "qwerty"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "loginEmail": "Hendrykkkk",
  "password": "qwerty"
}